<?php  //[STAMP] fcf6a3123748e77c8439382ec1b32697
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Paymentdrivers;

trait PaymentdriversTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
